

---

spring:
  config:
    activate:
      on-profile: "default"
graphql:
  packages:
    - "io.ekkles"
  subscriptions:
    # Send a ka message every 1000 ms (1 second)
    keepAliveInterval: 1000

